{% set version = "0.6.0" %}

package:
  name: pandas-flavor
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pandas_flavor/pandas_flavor-{{ version }}.tar.gz
  sha256: 9fb8735102dcb65dae7ee5cda12b393ca134a909ebcfc0262c5cdc1d79ba007f

build:
  number: 3
  noarch: python

outputs:
  - name: pandas-flavor
    script: build_base.sh
    requirements:
      host:
        - python {{ python_min }}
        - setuptools
        - pip
      run:
        - python >={{ python_min }}
        - pandas >=0.23
        - xarray
    test:
      imports:
        - pandas_flavor
      commands:
        - pip check
      requires:
        - pip

  - name: pandas_flavor
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('pandas-flavor', max_pin="x.x.x") }}
    test:
      imports:
        - pandas_flavor

about:
  home: https://github.com/Zsailer/pandas_flavor
  summary: The easy way to write your own Pandas flavor.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - zsailer
