{% set version = "0.2.0" %}

package:
  name: pandas-flavor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandas_flavor/pandas_flavor-{{ version }}.tar.gz
  sha256: 7871655816de22dc766e916697ccc67449e1863c090ef5fd40d4d0fbd056e489

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - python
    - pip
    - pandas
  run:
    - python
    - pandas

test:
  imports:
    - pandas_flavor

about:
  home: https://github.com/Zsailer/pandas_flavor
  license: MIT
  license_family: MIT
  # license_file: ''  No license file
  summary: The easy way to write your own Pandas flavor

extra:
  recipe-maintainers:
    - ocefpaf
