{% set version = "0.3.0" %}

package:
  name: pandas-flavor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandas_flavor/pandas_flavor-{{ version }}.tar.gz
  sha256: db5739481f5382b80cec3fd2905adeaaa0b03b8ed26912675b222a1d4a6672b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - lazy-loader ==0.1rc2
    - pandas >=0.23
    - xarray

test:
  imports:
    - pandas_flavor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Zsailer/pandas_flavor
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: The easy way to write your own Pandas flavor

extra:
  recipe-maintainers:
    - ocefpaf
    - zsailer
