{% set name = "pandas_flavor" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas_flavor-{{ version }}.tar.gz
  sha256: 9fb8735102dcb65dae7ee5cda12b393ca134a909ebcfc0262c5cdc1d79ba007f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas >=0.23
    - xarray
    - lazy_loader >=0.1

test:
  imports:
    - pandas_flavor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Zsailer/pandas_flavor
  summary: The easy way to write your own Pandas flavor.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - zsailer
