{% set version = "0.3.0" %}

package:
  name: pandas-flavor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pandas_flavor/pandas_flavor-{{ version }}.tar.gz
  sha256: db5739481f5382b80cec3fd2905adeaaa0b03b8ed26912675b222a1d4a6672b5

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - python
    - pip
    - pandas
    - xarray
  run:
    - python
    - pandas
    - xarray

test:
  imports:
    - pandas_flavor

about:
  home: https://github.com/Zsailer/pandas_flavor
  license: MIT
  license_file: LICENSE
  license_family: MIT
  # license_file: ''  No license file
  summary: The easy way to write your own Pandas flavor

extra:
  recipe-maintainers:
    - ocefpaf
    - zsailer
